services:
  ews_app:
    build: .
    container_name: ews_app
    ports:
      - "3000:3000"
    depends_on:
      - ews_db
    environment:
      - DATABASE_URL=postgresql://user_pijar:password_pijar@ews_db:5432/ews_malinau
    command: sh -c "sleep 10 && npx prisma db push && npx prisma db seed && npm run dev"

  ews_db:
    image: postgres:15-alpine
    container_name: ews_db
    environment:
      POSTGRES_USER: user_pijar
      POSTGRES_PASSWORD: password_pijar
      POSTGRES_DB: ews_malinau
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: